// 各ステージで使うポケモンのリスト
export const ENEMIES: {
  [key: string]: { id: string; name: string; inputName: string }[][];
} = {
  '01': [
    [
      { id: '0119', name: 'あずまおう', inputName: 'あす゛まおう' },
      { id: '0159', name: 'ありげいつ', inputName: 'ありけ゛いつ' },
      { id: '0168', name: 'ありあどす', inputName: 'ありあと゛す' },
      { id: '0201', name: 'あんのーん', inputName: 'あんのーん' },
      { id: '0255', name: 'あちゃも', inputName: 'あちゃも' },
      { id: '0267', name: 'あげはんと', inputName: 'あけ゛はんと' },
      { id: '0283', name: 'あめたま', inputName: 'あめたま' },
      { id: '0284', name: 'あめもーす', inputName: 'あめもーす' },
      { id: '0347', name: 'あのぷす', inputName: 'あのふ゜す' },
      { id: '0348', name: 'あーまるど', inputName: 'あーまると゛' },
      { id: '0359', name: 'あぶそる', inputName: 'あふ゛そる' },
      { id: '0482', name: 'あぐのむ', inputName: 'あく゛のむ' },
      { id: '0493', name: 'あるせうす', inputName: 'あるせうす' },
      { id: '0565', name: 'あばごーら', inputName: 'あは゛こ゛ーら' },
      { id: '0566', name: 'あーけん', inputName: 'あーけん' },
      { id: '0567', name: 'あーけおす', inputName: 'あーけおす' },
      { id: '0617', name: 'あぎるだー', inputName: 'あき゛るた゛ー' },
      { id: '0632', name: 'あいあんと', inputName: 'あいあんと' },
      { id: '0698', name: 'あまるす', inputName: 'あまるす' },
      { id: '0699', name: 'あまるるが', inputName: 'あまるるか゛' },
      { id: '0728', name: 'あしまり', inputName: 'あしまり' },
      { id: '0730', name: 'あしれーぬ', inputName: 'あしれーぬ' },
      { id: '0736', name: 'あごじむし', inputName: 'あこ゛し゛むし' },
      { id: '0742', name: 'あぶりー', inputName: 'あふ゛りー' },
      { id: '0743', name: 'あぶりぼん', inputName: 'あふ゛りほ゛ん' },
      { id: '0761', name: 'あまかじ', inputName: 'あまかし゛' },
      { id: '0762', name: 'あままいこ', inputName: 'あままいこ' },
      { id: '0763', name: 'あまーじょ', inputName: 'あまーし゛ょ' },
      { id: '0799', name: 'あくじきんぐ', inputName: 'あくし゛きんく゛' },
      { id: '0804', name: 'あーごよん', inputName: 'あーこ゛よん' },
      { id: '0822', name: 'あおがらす', inputName: 'あおか゛らす' },
      { id: '0823', name: 'あーまーがあ', inputName: 'あーまーか゛あ' },
      { id: '0841', name: 'あっぷりゅー', inputName: 'あっふ゜りゅー' },
      { id: '0899', name: 'あやしし', inputName: 'あやしし' },
      { id: '0910', name: 'あちげーた', inputName: 'あちけ゛ーた' },
      { id: '0946', name: 'あのくさ', inputName: 'あのくさ' },
      { id: '0947', name: 'あのほらぐさ', inputName: 'あのほらく゛さ' },
      { id: '0974', name: 'あるくじら', inputName: 'あるくし゛ら' },
      { id: '0986', name: 'あらぶるたけ', inputName: 'あらふ゛るたけ' },
    ],
    [
      { id: '0074', name: 'いしつぶて', inputName: 'いしつふ゛て' },
      { id: '0095', name: 'いわーく', inputName: 'いわーく' },
      { id: '0133', name: 'いーぶい', inputName: 'いーふ゛い' },
      { id: '0167', name: 'いとまる', inputName: 'いとまる' },
      { id: '0221', name: 'いのむー', inputName: 'いのむー' },
      { id: '0314', name: 'いるみーぜ', inputName: 'いるみーせ゛' },
      { id: '0557', name: 'いしずまい', inputName: 'いしす゛まい' },
      { id: '0558', name: 'いわぱれす', inputName: 'いわは゜れす' },
      { id: '0717', name: 'いべるたる', inputName: 'いへ゛るたる' },
      { id: '0744', name: 'いわんこ', inputName: 'いわんこ' },
      { id: '0818', name: 'いんてれおん', inputName: 'いんてれおん' },
      { id: '0826', name: 'いおるぶ', inputName: 'いおるふ゛' },
      { id: '0874', name: 'いしへんじん', inputName: 'いしへんし゛ん' },
      { id: '0876', name: 'いえっさん', inputName: 'いえっさん' },
      { id: '0876-1', name: 'いえっさん', inputName: 'いえっさん' },
      { id: '0902', name: 'いだいとう', inputName: 'いた゛いとう' },
      { id: '0902-1', name: 'いだいとう', inputName: 'いた゛いとう' },
      { id: '0925-1', name: 'いっかねずみ', inputName: 'いっかねす゛み' },
      { id: '0931', name: 'いきりんこ', inputName: 'いきりんこ' },
      { id: '0964', name: 'いるかまん', inputName: 'いるかまん' },
      { id: '0964-1', name: 'いるかまん', inputName: 'いるかまん' },
      { id: '0984', name: 'いだいなきば', inputName: 'いた゛いなきは゛' },
      { id: '1004', name: 'いーゆい', inputName: 'いーゆい' },
      { id: '1014', name: 'いいねいぬ', inputName: 'いいねいぬ' },
    ],
    [
      { id: '0070', name: 'うつどん', inputName: 'うつと゛ん' },
      { id: '0071', name: 'うつぼっと', inputName: 'うつほ゛っと' },
      { id: '0185', name: 'うそっきー', inputName: 'うそっきー' },
      { id: '0194', name: 'うぱー', inputName: 'うは゜ー' },
      { id: '0194-1', name: 'うぱー', inputName: 'うは゜ー' },
      { id: '0220', name: 'うりむー', inputName: 'うりむー' },
      { id: '0438', name: 'うそはち', inputName: 'うそはち' },
      { id: '0637', name: 'うるがもす', inputName: 'うるか゛もす' },
      { id: '0692', name: 'うでっぽう', inputName: 'うて゛っほ゜う' },
      { id: '0793', name: 'うつろいど', inputName: 'うつろいと゛' },
      { id: '0831', name: 'うーるー', inputName: 'うーるー' },
      { id: '0845', name: 'うっう', inputName: 'うっう' },
      { id: '0882', name: 'うおのらごん', inputName: 'うおのらこ゛ん' },
      { id: '0883', name: 'うおちるどん', inputName: 'うおちると゛ん' },
      { id: '0892', name: 'うーらおす', inputName: 'うーらおす' },
      { id: '0892-1', name: 'うーらおす', inputName: 'うーらおす' },
      { id: '0961', name: 'うみとりお', inputName: 'うみとりお' },
      { id: '1009', name: 'うねるみなも', inputName: 'うねるみなも' },
      { id: '1020', name: 'うがつほむら', inputName: 'うか゛つほむら' },
    ],
    [
      { id: '0107', name: 'えびわらー', inputName: 'えひ゛わらー' },
      { id: '0125', name: 'えれぶー', inputName: 'えれふ゛ー' },
      { id: '0190', name: 'えいぱむ', inputName: 'えいは゜む' },
      { id: '0227', name: 'えあーむど', inputName: 'えあーむと゛' },
      { id: '0239', name: 'えれきっど', inputName: 'えれきっと゛' },
      { id: '0244', name: 'えんてい', inputName: 'えんてい' },
      { id: '0300', name: 'えねこ', inputName: 'えねこ' },
      { id: '0301', name: 'えねころろ', inputName: 'えねころろ' },
      { id: '0395', name: 'えんぺると', inputName: 'えんへ゜ると' },
      { id: '0424', name: 'えてぼーす', inputName: 'えてほ゛ーす' },
      { id: '0466', name: 'えれきぶる', inputName: 'えれきふ゛る' },
      { id: '0475', name: 'えるれいど', inputName: 'えるれいと゛' },
      { id: '0481', name: 'えむりっと', inputName: 'えむりっと' },
      { id: '0500', name: 'えんぶおー', inputName: 'えんふ゛おー' },
      { id: '0547', name: 'えるふーん', inputName: 'えるふーん' },
      { id: '0587', name: 'えもんが', inputName: 'えもんか゛' },
      { id: '0694', name: 'えりきてる', inputName: 'えりきてる' },
      { id: '0695', name: 'えれざーど', inputName: 'えれさ゛ーと゛' },
      { id: '0758', name: 'えんにゅーと', inputName: 'えんにゅーと' },
      { id: '0815', name: 'えーすばーん', inputName: 'えーすは゛ーん' },
      { id: '0848', name: 'えれずん', inputName: 'えれす゛ん' },
      { id: '0920', name: 'えくすれっぐ', inputName: 'えくすれっく゛' },
    ],
    [
      { id: '0021', name: 'おにすずめ', inputName: 'おにすす゛め' },
      { id: '0022', name: 'おにどりる', inputName: 'おにと゛りる' },
      { id: '0057', name: 'おこりざる', inputName: 'おこりさ゛る' },
      { id: '0138', name: 'おむないと', inputName: 'おむないと' },
      { id: '0139', name: 'おむすたー', inputName: 'おむすたー' },
      { id: '0160', name: 'おーだいる', inputName: 'おーた゛いる' },
      { id: '0161', name: 'おたち', inputName: 'おたち' },
      { id: '0162', name: 'おおたち', inputName: 'おおたち' },
      { id: '0234', name: 'おどしし', inputName: 'おと゛しし' },
      { id: '0277', name: 'おおすばめ', inputName: 'おおすは゛め' },
      { id: '0362', name: 'おにごーり', inputName: 'おにこ゛ーり' },
      { id: '0535', name: 'おたまろ', inputName: 'おたまろ' },
      { id: '0606', name: 'おーべむ', inputName: 'おーへ゛む' },
      { id: '0611', name: 'おのんど', inputName: 'おのんと゛' },
      { id: '0612', name: 'おののくす', inputName: 'おののくす' },
      { id: '0709', name: 'おーろっと', inputName: 'おーろっと' },
      { id: '0714', name: 'おんばっと', inputName: 'おんは゛っと' },
      { id: '0715', name: 'おんばーん', inputName: 'おんは゛ーん' },
      { id: '0729', name: 'おしゃまり', inputName: 'おしゃまり' },
      { id: '0741', name: 'おどりどり', inputName: 'おと゛りと゛り' },
      { id: '0741-1', name: 'おどりどり', inputName: 'おと゛りと゛り' },
      { id: '0741-2', name: 'おどりどり', inputName: 'おと゛りと゛り' },
      { id: '0741-3', name: 'おどりどり', inputName: 'おと゛りと゛り' },
      { id: '0752', name: 'おにしずくも', inputName: 'おにしす゛くも' },
      { id: '0853', name: 'おとすぱす', inputName: 'おとすは゜す' },
      { id: '0861', name: 'おーろんげ', inputName: 'おーろんけ゛' },
      { id: '0903', name: 'おおにゅーら', inputName: 'おおにゅーら' },
      { id: '0929', name: 'おりーにょ', inputName: 'おりーにょ' },
      { id: '0942', name: 'おらちふ', inputName: 'おらちふ' },
      { id: '0962', name: 'おとしどり', inputName: 'おとしと゛り' },
      { id: '1017', name: 'おーがぽん', inputName: 'おーか゛ほ゜ん' },
      { id: '1017-1', name: 'おーがぽん', inputName: 'おーか゛ほ゜ん' },
      { id: '1017-2', name: 'おーがぽん', inputName: 'おーか゛ほ゜ん' },
      { id: '1017-3', name: 'おーがぽん', inputName: 'おーか゛ほ゜ん' },
    ],
  ],
  '02': [
    [
      { id: '0008', name: 'かめーる', inputName: 'かめーる' },
      { id: '0009', name: 'かめっくす', inputName: 'かめっくす' },
      { id: '0068', name: 'かいりきー', inputName: 'かいりきー' },
      { id: '0083', name: 'かもねぎ', inputName: 'かもねき゛' },
      { id: '0083-1', name: 'かもねぎ', inputName: 'かもねき゛' },
      { id: '0104', name: 'からから', inputName: 'からから' },
      { id: '0127', name: 'かいろす', inputName: 'かいろす' },
      { id: '0140', name: 'かぶと', inputName: 'かふ゛と' },
      { id: '0141', name: 'かぶとぷす', inputName: 'かふ゛とふ゜す' },
      { id: '0143', name: 'かびごん', inputName: 'かひ゛こ゛ん' },
      { id: '0149', name: 'かいりゅー', inputName: 'かいりゅー' },
      { id: '0237', name: 'かぽえらー', inputName: 'かほ゜えらー' },
      { id: '0266', name: 'からさりす', inputName: 'からさりす' },
      { id: '0352', name: 'かくれおん', inputName: 'かくれおん' },
      { id: '0353', name: 'かげぼうず', inputName: 'かけ゛ほ゛うす゛' },
      { id: '0382', name: 'かいおーが', inputName: 'かいおーか゛' },
      { id: '0422', name: 'からなくし', inputName: 'からなくし' },
      { id: '0422-1', name: 'からなくし', inputName: 'からなくし' },
      { id: '0450', name: 'かばるどん', inputName: 'かは゛ると゛ん' },
      { id: '0588', name: 'かぶるも', inputName: 'かふ゛るも' },
      { id: '0668', name: 'かえんじし', inputName: 'かえんし゛し' },
      { id: '0668-1', name: 'かえんじし', inputName: 'かえんし゛し' },
      { id: '0687', name: 'からまねろ', inputName: 'からまねろ' },
      { id: '0688', name: 'かめてて', inputName: 'かめてて' },
      { id: '0712', name: 'かちこーる', inputName: 'かちこーる' },
      { id: '0753', name: 'かりきり', inputName: 'かりきり' },
      { id: '0785', name: 'かぷこけこ', inputName: 'かふ゜こけこ' },
      { id: '0786', name: 'かぷててふ', inputName: 'かふ゜ててふ' },
      { id: '0787', name: 'かぷぶるる', inputName: 'かふ゜ふ゛るる' },
      { id: '0788', name: 'かぷれひれ', inputName: 'かふ゜れひれ' },
      { id: '0798', name: 'かみつるぎ', inputName: 'かみつるき゛' },
      { id: '0833', name: 'かむかめ', inputName: 'かむかめ' },
      { id: '0834', name: 'かじりがめ', inputName: 'かし゛りか゛め' },
      { id: '0840', name: 'かじっちゅ', inputName: 'かし゛っちゅ' },
      { id: '0847', name: 'かますじょー', inputName: 'かますし゛ょー' },
      { id: '0935', name: 'かるぼう', inputName: 'かるほ゛う' },
      { id: '0940', name: 'かいでん', inputName: 'かいて゛ん' },
      { id: '0951', name: 'かぷさいじ', inputName: 'かふ゜さいし゛' },
      { id: '0957', name: 'かぬちゃん', inputName: 'かぬちゃん' },
      { id: '0973', name: 'からみんご', inputName: 'からみんこ゛' },
      { id: '1011', name: 'かみっちゅ', inputName: 'かみっちゅ' },
      { id: '1019', name: 'かみつおろち', inputName: 'かみつおろち' },
    ],
    [
      { id: '0010', name: 'きゃたぴー', inputName: 'きゃたひ゜ー' },
      { id: '0038', name: 'きゅうこん', inputName: 'きゅうこん' },
      { id: '0038-1', name: 'きゅうこん', inputName: 'きゅうこん' },
      { id: '0099', name: 'きんぐらー', inputName: 'きんく゛らー' },
      { id: '0182', name: 'きれいはな', inputName: 'きれいはな' },
      { id: '0192', name: 'きまわり', inputName: 'きまわり' },
      { id: '0203', name: 'きりんりき', inputName: 'きりんりき' },
      { id: '0230', name: 'きんぐどら', inputName: 'きんく゛と゛ら' },
      { id: '0252', name: 'きもり', inputName: 'きもり' },
      { id: '0278', name: 'きゃもめ', inputName: 'きゃもめ' },
      { id: '0281', name: 'きるりあ', inputName: 'きるりあ' },
      { id: '0285', name: 'きのここ', inputName: 'きのここ' },
      { id: '0286', name: 'きのがっさ', inputName: 'きのか゛っさ' },
      { id: '0318', name: 'きばにあ', inputName: 'きは゛にあ' },
      { id: '0610', name: 'きばご', inputName: 'きは゛こ゛' },
      { id: '0625', name: 'きりきざん', inputName: 'きりきさ゛ん' },
      { id: '0646-1', name: 'きゅれむ', inputName: 'きゅれむ' },
      { id: '0646-2', name: 'きゅれむ', inputName: 'きゅれむ' },
      { id: '0760', name: 'きてるぐま', inputName: 'きてるく゛ま' },
      { id: '0764', name: 'きゅわわー', inputName: 'きゅわわー' },
      { id: '0934', name: 'きょじおーん', inputName: 'きょし゛おーん' },
      { id: '0969', name: 'きらーめ', inputName: 'きらーめ' },
      { id: '0970', name: 'きらふろる', inputName: 'きらふろる' },
      { id: '1016', name: 'きちきぎす', inputName: 'きちきき゛す' },
    ],
    [
      { id: '0044', name: 'くさいはな', inputName: 'くさいはな' },
      { id: '0098', name: 'くらぶ', inputName: 'くらふ゛' },
      { id: '0169', name: 'くろばっと', inputName: 'くろは゛っと' },
      { id: '0204', name: 'くぬぎだま', inputName: 'くぬき゛た゛ま' },
      { id: '0303', name: 'くちーと', inputName: 'くちーと' },
      { id: '0488', name: 'くれせりあ', inputName: 'くれせりあ' },
      { id: '0540', name: 'くるみる', inputName: 'くるみる' },
      { id: '0541', name: 'くるまゆ', inputName: 'くるまゆ' },
      { id: '0613', name: 'くましゅん', inputName: 'くましゅん' },
      { id: '0621', name: 'くりむがん', inputName: 'くりむか゛ん' },
      { id: '0631', name: 'くいたらん', inputName: 'くいたらん' },
      { id: '0690', name: 'くずもー', inputName: 'くす゛もー' },
      { id: '0713', name: 'くれべーす', inputName: 'くれへ゛ーす' },
      { id: '0713-1', name: 'くれべーす', inputName: 'くれへ゛ーす' },
      { id: '0738', name: 'くわがのん', inputName: 'くわか゛のん' },
      { id: '0827', name: 'くすね', inputName: 'くすね' },
      { id: '0912', name: 'くわっす', inputName: 'くわっす' },
      { id: '0956', name: 'くえすぱとら', inputName: 'くえすは゜とら' },
    ],
    [
      { id: '0128', name: 'けんたろす', inputName: 'けんたろす' },
      { id: '0128-1', name: 'けんたろす', inputName: 'けんたろす' },
      { id: '0128-2', name: 'けんたろす', inputName: 'けんたろす' },
      { id: '0128-3', name: 'けんたろす', inputName: 'けんたろす' },
      { id: '0265', name: 'けむっそ', inputName: 'けむっそ' },
      { id: '0289', name: 'けっきんぐ', inputName: 'けっきんく゛' },
      { id: '0456', name: 'けいこうお', inputName: 'けいこうお' },
      { id: '0521', name: 'けんほろう', inputName: 'けんほろう' },
      { id: '0521-1', name: 'けんほろう', inputName: 'けんほろう' },
      { id: '0656', name: 'けろまつ', inputName: 'けろまつ' },
      { id: '0732', name: 'けららっぱ', inputName: 'けららっは゜' },
      { id: '0740', name: 'けけんかに', inputName: 'けけんかに' },
    ],
    [
      { id: '0014', name: 'こくーん', inputName: 'こくーん' },
      { id: '0019', name: 'こらった', inputName: 'こらった' },
      { id: '0019-1', name: 'こらった', inputName: 'こらった' },
      { id: '0048', name: 'こんぱん', inputName: 'こんは゜ん' },
      { id: '0054', name: 'こだっく', inputName: 'こた゛っく' },
      { id: '0081', name: 'こいる', inputName: 'こいる' },
      { id: '0129', name: 'こいきんぐ', inputName: 'こいきんく゛' },
      { id: '0274', name: 'このはな', inputName: 'このはな' },
      { id: '0304', name: 'ここどら', inputName: 'ここと゛ら' },
      { id: '0305', name: 'こどら', inputName: 'こと゛ら' },
      { id: '0324', name: 'こーたす', inputName: 'こーたす' },
      { id: '0372', name: 'こもるー', inputName: 'こもるー' },
      { id: '0401', name: 'ころぼーし', inputName: 'ころほ゛ーし' },
      { id: '0402', name: 'ころとっく', inputName: 'ころとっく' },
      { id: '0403', name: 'こりんく', inputName: 'こりんく' },
      { id: '0527', name: 'ころもり', inputName: 'ころもり' },
      { id: '0528', name: 'こころもり', inputName: 'こころもり' },
      { id: '0580', name: 'こあるひー', inputName: 'こあるひー' },
      { id: '0619', name: 'こじょふー', inputName: 'こし゛ょふー' },
      { id: '0620', name: 'こじょんど', inputName: 'こし゛ょんと゛' },
      { id: '0624', name: 'こまたな', inputName: 'こまたな' },
      { id: '0638', name: 'こばるおん', inputName: 'こは゛るおん' },
      { id: '0664', name: 'こふきむし', inputName: 'こふきむし' },
      { id: '0665', name: 'こふーらい', inputName: 'こふーらい' },
      { id: '0767', name: 'こそくむし', inputName: 'こそくむし' },
      { id: '0789', name: 'こすもっぐ', inputName: 'こすもっく゛' },
      { id: '0790', name: 'こすもうむ', inputName: 'こすもうむ' },
      { id: '0821', name: 'ここがら', inputName: 'ここか゛ら' },
      { id: '0875', name: 'こおりっぽ', inputName: 'こおりっほ゜' },
      { id: '0875-1', name: 'こおりっぽ', inputName: 'こおりっほ゜' },
      { id: '0932', name: 'こじお', inputName: 'こし゛お' },
      { id: '0979', name: 'このよざる', inputName: 'このよさ゛る' },
      { id: '0999', name: 'これくれー', inputName: 'これくれー' },
      { id: '0999-1', name: 'これくれー', inputName: 'これくれー' },
      { id: '1007', name: 'こらいどん', inputName: 'こらいと゛ん' },
    ],
  ],
  '03': [
    [
      { id: '0027', name: 'さんど', inputName: 'さんと゛' },
      { id: '0027-1', name: 'さんど', inputName: 'さんと゛' },
      { id: '0028', name: 'さんどぱん', inputName: 'さんと゛は゜ん' },
      { id: '0028-1', name: 'さんどぱん', inputName: 'さんと゛は゜ん' },
      { id: '0106', name: 'さわむらー', inputName: 'さわむらー' },
      { id: '0111', name: 'さいほーん', inputName: 'さいほーん' },
      { id: '0112', name: 'さいどん', inputName: 'さいと゛ん' },
      { id: '0135', name: 'さんだーす', inputName: 'さんた゛ーす' },
      { id: '0145', name: 'さんだー', inputName: 'さんた゛ー' },
      { id: '0145-1', name: 'さんだー', inputName: 'さんた゛ー' },
      { id: '0222', name: 'さにーご', inputName: 'さにーこ゛' },
      { id: '0222-1', name: 'さにーご', inputName: 'さにーこ゛' },
      { id: '0247', name: 'さなぎらす', inputName: 'さなき゛らす' },
      { id: '0282', name: 'さーないと', inputName: 'さーないと' },
      { id: '0319', name: 'さめはだー', inputName: 'さめはた゛ー' },
      { id: '0331', name: 'さぼねあ', inputName: 'さほ゛ねあ' },
      { id: '0356', name: 'さまよーる', inputName: 'さまよーる' },
      { id: '0368', name: 'さくらびす', inputName: 'さくらひ゛す' },
      { id: '0635', name: 'さざんどら', inputName: 'ささ゛んと゛ら' },
      { id: '0810', name: 'さるのり', inputName: 'さるのり' },
      { id: '0824', name: 'さっちむし', inputName: 'さっちむし' },
      { id: '0844', name: 'さだいじゃ', inputName: 'さた゛いし゛ゃ' },
      { id: '0846', name: 'さしかます', inputName: 'さしかます' },
      { id: '0864', name: 'さにごーん', inputName: 'さにこ゛ーん' },
      { id: '0985', name: 'さけぶしっぽ', inputName: 'さけふ゛しっほ゜' },
      { id: '1000', name: 'さーふごー', inputName: 'さーふこ゛ー' },
    ],
    [
      { id: '0117', name: 'しーどら', inputName: 'しーと゛ら' },
      { id: '0134', name: 'しゃわーず', inputName: 'しゃわーす゛' },
      { id: '0342', name: 'しざりがー', inputName: 'しさ゛りか゛ー' },
      { id: '0522', name: 'しまま', inputName: 'しまま' },
      { id: '0561', name: 'しんぼらー', inputName: 'しんほ゛らー' },
      { id: '0585', name: 'しきじか', inputName: 'しきし゛か' },
      { id: '0585-1', name: 'しきじか', inputName: 'しきし゛か' },
      { id: '0585-2', name: 'しきじか', inputName: 'しきし゛か' },
      { id: '0585-3', name: 'しきじか', inputName: 'しきし゛か' },
      { id: '0589', name: 'しゅばるご', inputName: 'しゅは゛るこ゛' },
      { id: '0602', name: 'しびしらす', inputName: 'しひ゛しらす' },
      { id: '0603', name: 'しびびーる', inputName: 'しひ゛ひ゛ーる' },
      { id: '0604', name: 'しびるどん', inputName: 'しひ゛ると゛ん' },
      { id: '0609', name: 'しゃんでら', inputName: 'しゃんて゛ら' },
      { id: '0667', name: 'ししこ', inputName: 'ししこ' },
      { id: '0682', name: 'しゅしゅぷ', inputName: 'しゅしゅふ゜' },
      { id: '0751', name: 'しずくも', inputName: 'しす゛くも' },
      { id: '0770', name: 'しろですな', inputName: 'しろて゛すな' },
      { id: '0944', name: 'しるしゅるー', inputName: 'しるしゅるー' },
      { id: '0953', name: 'しがろこ', inputName: 'しか゛ろこ' },
      { id: '0978', name: 'しゃりたつ', inputName: 'しゃりたつ' },
      { id: '0978-1', name: 'しゃりたつ', inputName: 'しゃりたつ' },
      { id: '0978-2', name: 'しゃりたつ', inputName: 'しゃりたつ' },
    ],
    [
      { id: '0015', name: 'すぴあー', inputName: 'すひ゜あー' },
      { id: '0096', name: 'すりーぷ', inputName: 'すりーふ゜' },
      { id: '0097', name: 'すりーぱー', inputName: 'すりーは゜ー' },
      { id: '0121', name: 'すたーみー', inputName: 'すたーみー' },
      { id: '0123', name: 'すとらいく', inputName: 'すとらいく' },
      { id: '0245', name: 'すいくん', inputName: 'すいくん' },
      { id: '0276', name: 'すばめ', inputName: 'すは゛め' },
      { id: '0406', name: 'すぼみー', inputName: 'すほ゛みー' },
      { id: '0434', name: 'すかんぷー', inputName: 'すかんふ゜ー' },
      { id: '0435', name: 'すかたんく', inputName: 'すかたんく' },
      { id: '0451', name: 'すこるぴ', inputName: 'すこるひ゜' },
      { id: '0581', name: 'すわんな', inputName: 'すわんな' },
      { id: '0843', name: 'すなへび', inputName: 'すなへひ゛' },
      { id: '0849', name: 'すとりんだー', inputName: 'すとりんた゛ー' },
      { id: '0849-1', name: 'すとりんだー', inputName: 'すとりんた゛ー' },
      { id: '0989', name: 'すなのけがわ', inputName: 'すなのけか゛わ' },
    ],
    [
      { id: '0839', name: 'せきたんざん', inputName: 'せきたんさ゛ん' },
      { id: '0996', name: 'せびえ', inputName: 'せひ゛え' },
      { id: '0997', name: 'せごーる', inputName: 'せこ゛ーる' },
      { id: '0998', name: 'せぐれいぶ', inputName: 'せく゛れいふ゛' },
    ],
    [
      { id: '0202', name: 'そーなんす', inputName: 'そーなんす' },
      { id: '0338', name: 'そるろっく', inputName: 'そるろっく' },
      { id: '0360', name: 'そーなの', inputName: 'そーなの' },
      { id: '0791', name: 'そるがれお', inputName: 'そるか゛れお' },
      { id: '0937', name: 'そうぶれいず', inputName: 'そうふ゛れいす゛' },
    ],
  ],
  '04': [
    [
      { id: '0102', name: 'たまたま', inputName: 'たまたま' },
      { id: '0116', name: 'たっつー', inputName: 'たっつー' },
      { id: '0273', name: 'たねぼー', inputName: 'たねほ゛ー' },
      { id: '0363', name: 'たまざらし', inputName: 'たまさ゛らし' },
      { id: '0371', name: 'たつべい', inputName: 'たつへ゛い' },
      { id: '0410', name: 'たてとぷす', inputName: 'たてとふ゜す' },
      { id: '0458', name: 'たまんた', inputName: 'たまんた' },
      { id: '0531', name: 'たぶんね', inputName: 'たふ゛んね' },
      { id: '0590', name: 'たまげたけ', inputName: 'たまけ゛たけ' },
      { id: '0772', name: 'たいぷ：ぬる', inputName: 'たいふ゜：ぬる' },
      { id: '0837', name: 'たんどん', inputName: 'たんと゛ん' },
      { id: '0842', name: 'たるっぷる', inputName: 'たるっふ゜る' },
      { id: '0852', name: 'たたっこ', inputName: 'たたっこ' },
      { id: '0862', name: 'たちふさぐま', inputName: 'たちふさく゛ま' },
      { id: '0870', name: 'たいれーつ', inputName: 'たいれーつ' },
      { id: '0917', name: 'たまんちゅら', inputName: 'たまんちゅら' },
      { id: '0941', name: 'たいかいでん', inputName: 'たいかいて゛ん' },
      { id: '0945', name: 'たぎんぐる', inputName: 'たき゛んく゛る' },
      { id: '1021', name: 'たけるらいこ', inputName: 'たけるらいこ' },
    ],
    [
      { id: '0152', name: 'ちこりーた', inputName: 'ちこりーた' },
      { id: '0170', name: 'ちょんちー', inputName: 'ちょんちー' },
      { id: '0308', name: 'ちゃーれむ', inputName: 'ちゃーれむ' },
      { id: '0333', name: 'ちるっと', inputName: 'ちるっと' },
      { id: '0334', name: 'ちるたりす', inputName: 'ちるたりす' },
      { id: '0358', name: 'ちりーん', inputName: 'ちりーん' },
      { id: '0499', name: 'ちゃおぶー', inputName: 'ちゃおふ゛ー' },
      { id: '0509', name: 'ちょろねこ', inputName: 'ちょろねこ' },
      { id: '0548', name: 'ちゅりね', inputName: 'ちゅりね' },
      { id: '0573', name: 'ちらちーの', inputName: 'ちらちーの' },
      { id: '0616', name: 'ちょぼまき', inputName: 'ちょほ゛まき' },
      { id: '0696', name: 'ちごらす', inputName: 'ちこ゛らす' },
      { id: '1012', name: 'ちゃです', inputName: 'ちゃて゛す' },
    ],
    [
      { id: '0213', name: 'つぼつぼ', inputName: 'つほ゛つほ゛' },
      { id: '0290', name: 'つちにん', inputName: 'つちにん' },
      { id: '0495', name: 'つたーじゃ', inputName: 'つたーし゛ゃ' },
      { id: '0614', name: 'つんべあー', inputName: 'つんへ゛あー' },
      { id: '0731', name: 'つつけら', inputName: 'つつけら' },
      { id: '0805', name: 'つんでつんで', inputName: 'つんて゛つんて゛' },
    ],
    [
      { id: '0223', name: 'てっぽうお', inputName: 'てっほ゜うお' },
      { id: '0291', name: 'てっかにん', inputName: 'てっかにん' },
      { id: '0597', name: 'てっしーど', inputName: 'てっしーと゛' },
      { id: '0639', name: 'てらきおん', inputName: 'てらきおん' },
      { id: '0654', name: 'てーるなー', inputName: 'てーるなー' },
      { id: '0797', name: 'てっかぐや', inputName: 'てっかく゛や' },
      { id: '0857', name: 'てぶりむ', inputName: 'てふ゛りむ' },
      { id: '0990', name: 'てつのわだち', inputName: 'てつのわた゛ち' },
      { id: '0991', name: 'てつのつつみ', inputName: 'てつのつつみ' },
      { id: '0992', name: 'てつのかいな', inputName: 'てつのかいな' },
      { id: '0993', name: 'てつのこうべ', inputName: 'てつのこうへ゛' },
      { id: '0994', name: 'てつのどくが', inputName: 'てつのと゛くか゛' },
      { id: '0995', name: 'てつのいばら', inputName: 'てつのいは゛ら' },
      { id: '1006', name: 'てつのぶじん', inputName: 'てつのふ゛し゛ん' },
      { id: '1010', name: 'てつのいさは', inputName: 'てつのいさは' },
      { id: '1022', name: 'てつのいわお', inputName: 'てつのいわお' },
      { id: '1023', name: 'てつのかしら', inputName: 'てつのかしら' },
    ],
    [
      { id: '0011', name: 'とらんせる', inputName: 'とらんせる' },
      { id: '0118', name: 'とさきんと', inputName: 'とさきんと' },
      { id: '0175', name: 'とげぴー', inputName: 'とけ゛ひ゜ー' },
      { id: '0176', name: 'とげちっく', inputName: 'とけ゛ちっく' },
      { id: '0357', name: 'とろぴうす', inputName: 'とろひ゜うす' },
      { id: '0364', name: 'とどぐらー', inputName: 'とと゛く゛らー' },
      { id: '0365', name: 'とどぜるが', inputName: 'とと゛せ゛るか゛' },
      { id: '0411', name: 'とりでぷす', inputName: 'とりて゛ふ゜す' },
      { id: '0423', name: 'とりとどん', inputName: 'とりとと゛ん' },
      { id: '0423-1', name: 'とりとどん', inputName: 'とりとと゛ん' },
      { id: '0468', name: 'とげきっす', inputName: 'とけ゛きっす' },
      { id: '0641', name: 'とるねろす', inputName: 'とるねろす' },
      { id: '0641-1', name: 'とるねろす', inputName: 'とるねろす' },
      { id: '0676', name: 'とりみあん', inputName: 'とりみあん' },
      { id: '0777', name: 'とげでまる', inputName: 'とけ゛て゛まる' },
      { id: '0838', name: 'とろっごん', inputName: 'とろっこ゛ん' },
      { id: '1005', name: 'とどろくつき', inputName: 'とと゛ろくつき' },
    ],
  ],
  '05': [
    [
      { id: '0043', name: 'なぞのくさ', inputName: 'なそ゛のくさ' },
      { id: '0103', name: 'なっしー', inputName: 'なっしー' },
      { id: '0103-1', name: 'なっしー', inputName: 'なっしー' },
      { id: '0287', name: 'なまけろ', inputName: 'なまけろ' },
      { id: '0328', name: 'なっくらー', inputName: 'なっくらー' },
      { id: '0340', name: 'なまずん', inputName: 'なます゛ん' },
      { id: '0387', name: 'なえとる', inputName: 'なえとる' },
      { id: '0538', name: 'なげき', inputName: 'なけ゛き' },
      { id: '0598', name: 'なっとれい', inputName: 'なっとれい' },
      { id: '0766', name: 'なげつけさる', inputName: 'なけ゛つけさる' },
      { id: '0771', name: 'なまこぶし', inputName: 'なまこふ゛し' },
      { id: '0958', name: 'なかぬちゃん', inputName: 'なかぬちゃん' },
      { id: '0963', name: 'なみいるか', inputName: 'なみいるか' },
    ],
    [
      { id: '0029', name: 'にどらん', inputName: 'にと゛らん' },
      { id: '0030', name: 'にどりーな', inputName: 'にと゛りーな' },
      { id: '0031', name: 'にどくいん', inputName: 'にと゛くいん' },
      { id: '0032', name: 'にどらん', inputName: 'にと゛らん' },
      { id: '0033', name: 'にどりーの', inputName: 'にと゛りーの' },
      { id: '0034', name: 'にどきんぐ', inputName: 'にと゛きんく゛' },
      { id: '0052', name: 'にゃーす', inputName: 'にゃーす' },
      { id: '0052-1', name: 'にゃーす', inputName: 'にゃーす' },
      { id: '0052-2', name: 'にゃーす', inputName: 'にゃーす' },
      { id: '0060', name: 'にょろも', inputName: 'にょろも' },
      { id: '0061', name: 'にょろぞ', inputName: 'にょろそ゛' },
      { id: '0062', name: 'にょろぼん', inputName: 'にょろほ゛ん' },
      { id: '0186', name: 'にょろとの', inputName: 'にょろとの' },
      { id: '0215', name: 'にゅーら', inputName: 'にゅーら' },
      { id: '0215-1', name: 'にゅーら', inputName: 'にゅーら' },
      { id: '0431', name: 'にゃるまー', inputName: 'にゃるまー' },
      { id: '0677', name: 'にゃすぱー', inputName: 'にゃすは゜ー' },
      { id: '0678', name: 'にゃおにくす', inputName: 'にゃおにくす' },
      { id: '0678-1', name: 'にゃおにくす', inputName: 'にゃおにくす' },
      { id: '0680', name: 'にだんぎる', inputName: 'にた゛んき゛る' },
      { id: '0725', name: 'にゃびー', inputName: 'にゃひ゛ー' },
      { id: '0726', name: 'にゃひーと', inputName: 'にゃひーと' },
      { id: '0863', name: 'にゃいきんぐ', inputName: 'にゃいきんく゛' },
      { id: '0906', name: 'にゃおは', inputName: 'にゃおは' },
      { id: '0907', name: 'にゃろーて', inputName: 'にゃろーて' },
    ],
    [
      { id: '0195', name: 'ぬおー', inputName: 'ぬおー' },
      { id: '0259', name: 'ぬまくろー', inputName: 'ぬまくろー' },
      { id: '0292', name: 'ぬけにん', inputName: 'ぬけにん' },
      { id: '0704', name: 'ぬめら', inputName: 'ぬめら' },
      { id: '0705', name: 'ぬめいる', inputName: 'ぬめいる' },
      { id: '0705-1', name: 'ぬめいる', inputName: 'ぬめいる' },
      { id: '0706', name: 'ぬめるごん', inputName: 'ぬめるこ゛ん' },
      { id: '0706-1', name: 'ぬめるごん', inputName: 'ぬめるこ゛ん' },
      { id: '0759', name: 'ぬいこぐま', inputName: 'ぬいこく゛ま' },
    ],
    [
      { id: '0344', name: 'ねんどーる', inputName: 'ねんと゛ーる' },
      { id: '0457', name: 'ねおらんと', inputName: 'ねおらんと' },
      { id: '0755', name: 'ねましゅ', inputName: 'ねましゅ' },
      { id: '0775', name: 'ねっこあら', inputName: 'ねっこあら' },
      { id: '0800', name: 'ねくろずま', inputName: 'ねくろす゛ま' },
      { id: '0800-1', name: 'ねくろずま', inputName: 'ねくろす゛ま' },
      { id: '0800-2', name: 'ねくろずま', inputName: 'ねくろす゛ま' },
      { id: '0865', name: 'ねぎがないと', inputName: 'ねき゛か゛ないと' },
    ],
    [
      { id: '0206', name: 'のこっち', inputName: 'のこっち' },
      { id: '0299', name: 'のずぱす', inputName: 'のす゛は゜す' },
      { id: '0332', name: 'のくたす', inputName: 'のくたす' },
      { id: '0948', name: 'ののくらげ', inputName: 'ののくらけ゛' },
      { id: '0982', name: 'のここっち', inputName: 'のここっち' },
    ],
  ],
  '06': [
    [
      { id: '0148', name: 'はくりゅー', inputName: 'はくりゅー' },
      { id: '0187', name: 'はねっこ', inputName: 'はねっこ' },
      { id: '0208', name: 'はがねーる', inputName: 'はか゛ねーる' },
      { id: '0211', name: 'はりーせん', inputName: 'はりーせん' },
      { id: '0211-1', name: 'はりーせん', inputName: 'はりーせん' },
      { id: '0212', name: 'はっさむ', inputName: 'はっさむ' },
      { id: '0242', name: 'はぴなす', inputName: 'はひ゜なす' },
      { id: '0270', name: 'はすぼー', inputName: 'はすほ゛ー' },
      { id: '0271', name: 'はすぶれろ', inputName: 'はすふ゛れろ' },
      { id: '0297', name: 'はりてやま', inputName: 'はりてやま' },
      { id: '0336', name: 'はぶねーく', inputName: 'はふ゛ねーく' },
      { id: '0367', name: 'はんてーる', inputName: 'はんてーる' },
      { id: '0388', name: 'はやしがめ', inputName: 'はやしか゛め' },
      { id: '0507', name: 'はーでりあ', inputName: 'はーて゛りあ' },
      { id: '0520', name: 'はとーぼー', inputName: 'はとーほ゛ー' },
      { id: '0542', name: 'ははこもり', inputName: 'ははこもり' },
      { id: '0650', name: 'はりまろん', inputName: 'はりまろん' },
      { id: '0651', name: 'はりぼーぐ', inputName: 'はりほ゛ーく゛' },
      { id: '0779', name: 'はぎぎしり', inputName: 'はき゛き゛しり' },
      { id: '0904', name: 'はりーまん', inputName: 'はりーまん' },
      { id: '0939', name: 'はらばりー', inputName: 'はらは゛りー' },
      { id: '0972', name: 'はかどっぐ', inputName: 'はかと゛っく゛' },
      { id: '0975', name: 'はるくじら', inputName: 'はるくし゛ら' },
      { id: '0987', name: 'はばたくかみ', inputName: 'はは゛たくかみ' },
    ],
    [
      { id: '0004', name: 'ひとかげ', inputName: 'ひとかけ゛' },
      { id: '0120', name: 'ひとでまん', inputName: 'ひとて゛まん' },
      { id: '0155', name: 'ひのあらし', inputName: 'ひのあらし' },
      { id: '0191', name: 'ひまなっつ', inputName: 'ひまなっつ' },
      { id: '0216', name: 'ひめぐま', inputName: 'ひめく゛ま' },
      { id: '0349', name: 'ひんばす', inputName: 'ひんは゛す' },
      { id: '0390', name: 'ひこざる', inputName: 'ひこさ゛る' },
      { id: '0449', name: 'ひぽぽたす', inputName: 'ひほ゜ほ゜たす' },
      { id: '0485', name: 'ひーどらん', inputName: 'ひーと゛らん' },
      { id: '0515', name: 'ひやっぷ', inputName: 'ひやっふ゜' },
      { id: '0516', name: 'ひやっきー', inputName: 'ひやっきー' },
      { id: '0555', name: 'ひひだるま', inputName: 'ひひた゛るま' },
      { id: '0555-2', name: 'ひひだるま', inputName: 'ひひた゛るま' },
      { id: '0607', name: 'ひともし', inputName: 'ひともし' },
      { id: '0662', name: 'ひのやこま', inputName: 'ひのやこま' },
      { id: '0679', name: 'ひとつき', inputName: 'ひとつき' },
      { id: '0747', name: 'ひどいで', inputName: 'ひと゛いて゛' },
      { id: '0813', name: 'ひばにー', inputName: 'ひは゛にー' },
      { id: '0829', name: 'ひめんか', inputName: 'ひめんか' },
      { id: '0955', name: 'ひらひな', inputName: 'ひらひな' },
    ],
    [
      { id: '0001', name: 'ふしぎだね', inputName: 'ふしき゛た゛ね' },
      { id: '0002', name: 'ふしぎそう', inputName: 'ふしき゛そう' },
      { id: '0003', name: 'ふしぎばな', inputName: 'ふしき゛は゛な' },
      { id: '0144', name: 'ふりーざー', inputName: 'ふりーさ゛ー' },
      { id: '0144-1', name: 'ふりーざー', inputName: 'ふりーさ゛ー' },
      { id: '0330', name: 'ふらいごん', inputName: 'ふらいこ゛ん' },
      { id: '0419', name: 'ふろーぜる', inputName: 'ふろーせ゛る' },
      { id: '0425', name: 'ふわんて', inputName: 'ふわんて' },
      { id: '0426', name: 'ふわらいど', inputName: 'ふわらいと゛' },
      { id: '0443', name: 'ふかまる', inputName: 'ふかまる' },
      { id: '0502', name: 'ふたちまる', inputName: 'ふたちまる' },
      { id: '0543', name: 'ふしで', inputName: 'ふして゛' },
      { id: '0615', name: 'ふりーじお', inputName: 'ふりーし゛お' },
      { id: '0669', name: 'ふらべべ', inputName: 'ふらへ゛へ゛' },
      { id: '0670', name: 'ふらえって', inputName: 'ふらえって' },
      { id: '0683', name: 'ふれふわん', inputName: 'ふれふわん' },
      { id: '0720', name: 'ふーぱ', inputName: 'ふーは゜' },
      { id: '0720-1', name: 'ふーぱ', inputName: 'ふーは゜' },
      { id: '0723', name: 'ふくすろー', inputName: 'ふくすろー' },
    ],
    [
      { id: '0214', name: 'へらくろす', inputName: 'へらくろす' },
      { id: '0229', name: 'へるがー', inputName: 'へるか゛ー' },
      { id: '0341', name: 'へいがに', inputName: 'へいか゛に' },
      { id: '0977', name: 'へいらっしゃ', inputName: 'へいらっしゃ' },
    ],
    [
      { id: '0163', name: 'ほーほー', inputName: 'ほーほー' },
      { id: '0250', name: 'ほうおう', inputName: 'ほうおう' },
      { id: '0320', name: 'ほえるこ', inputName: 'ほえるこ' },
      { id: '0321', name: 'ほえるおー', inputName: 'ほえるおー' },
      { id: '0544', name: 'ほいーが', inputName: 'ほいーか゛' },
      { id: '0659', name: 'ほるびー', inputName: 'ほるひ゛ー' },
      { id: '0660', name: 'ほるーど', inputName: 'ほるーと゛' },
      { id: '0819', name: 'ほしがりす', inputName: 'ほしか゛りす' },
      { id: '0909', name: 'ほげーた', inputName: 'ほけ゛ーた' },
    ],
  ],
  '07': [
    [
      { id: '0056', name: 'まんきー', inputName: 'まんきー' },
      { id: '0069', name: 'まだつぼみ', inputName: 'また゛つほ゛み' },
      { id: '0101', name: 'まるまいん', inputName: 'まるまいん' },
      { id: '0101-1', name: 'まるまいん', inputName: 'まるまいん' },
      { id: '0110', name: 'またどがす', inputName: 'またと゛か゛す' },
      { id: '0110-1', name: 'またどがす', inputName: 'またと゛か゛す' },
      { id: '0156', name: 'まぐまらし', inputName: 'まく゛まらし' },
      { id: '0183', name: 'まりる', inputName: 'まりる' },
      { id: '0184', name: 'まりるり', inputName: 'まりるり' },
      { id: '0218', name: 'まぐまっぐ', inputName: 'まく゛まっく゛' },
      { id: '0219', name: 'まぐかるご', inputName: 'まく゛かるこ゛' },
      { id: '0226', name: 'まんたいん', inputName: 'まんたいん' },
      { id: '0264', name: 'まっすぐま', inputName: 'まっすく゛ま' },
      { id: '0264-1', name: 'まっすぐま', inputName: 'まっすく゛ま' },
      { id: '0268', name: 'まゆるど', inputName: 'まゆると゛' },
      { id: '0296', name: 'まくのした', inputName: 'まくのした' },
      { id: '0312', name: 'まいなん', inputName: 'まいなん' },
      { id: '0317', name: 'まるのーむ', inputName: 'まるのーむ' },
      { id: '0439', name: 'まねね', inputName: 'まねね' },
      { id: '0455', name: 'ますきっぱ', inputName: 'ますきっは゜' },
      { id: '0461', name: 'まにゅーら', inputName: 'まにゅーら' },
      { id: '0473', name: 'まんむー', inputName: 'まんむー' },
      { id: '0519', name: 'まめぱと', inputName: 'まめは゜と' },
      { id: '0556', name: 'まらかっち', inputName: 'まらかっち' },
      { id: '0594', name: 'ままんぼう', inputName: 'ままんほ゛う' },
      { id: '0618', name: 'まっぎょ', inputName: 'まっき゛ょ' },
      { id: '0618-1', name: 'まっぎょ', inputName: 'まっき゛ょ' },
      { id: '0686', name: 'まーいーか', inputName: 'まーいーか' },
      { id: '0739', name: 'まけんかに', inputName: 'まけんかに' },
      { id: '0794', name: 'まっしぶーん', inputName: 'まっしふ゛ーん' },
      { id: '0801', name: 'まぎあな', inputName: 'まき゛あな' },
      { id: '0802', name: 'まーしゃどー', inputName: 'まーしゃと゛ー' },
      { id: '0851', name: 'まるやくで', inputName: 'まるやくて゛' },
      { id: '0868', name: 'まほみる', inputName: 'まほみる' },
      { id: '0869', name: 'まほいっぷ', inputName: 'まほいっふ゜' },
      { id: '0908', name: 'ますかーにゃ', inputName: 'ますかーにゃ' },
      { id: '0919', name: 'まめばった', inputName: 'まめは゛った' },
      { id: '1015', name: 'ましましら', inputName: 'ましましら' },
    ],
    [
      { id: '0147', name: 'みにりゅう', inputName: 'みにりゅう' },
      { id: '0150', name: 'みゅうつー', inputName: 'みゅうつー' },
      { id: '0151', name: 'みゅう', inputName: 'みゅう' },
      { id: '0241', name: 'みるたんく', inputName: 'みるたんく' },
      { id: '0258', name: 'みずごろう', inputName: 'みす゛こ゛ろう' },
      { id: '0350', name: 'みろかろす', inputName: 'みろかろす' },
      { id: '0412', name: 'みのむっち', inputName: 'みのむっち' },
      { id: '0412-1', name: 'みのむっち', inputName: 'みのむっち' },
      { id: '0412-2', name: 'みのむっち', inputName: 'みのむっち' },
      { id: '0413', name: 'みのまだむ', inputName: 'みのまた゛む' },
      { id: '0413-1', name: 'みのまだむ', inputName: 'みのまた゛む' },
      { id: '0413-2', name: 'みのまだむ', inputName: 'みのまた゛む' },
      { id: '0415', name: 'みつはにー', inputName: 'みつはにー' },
      { id: '0427', name: 'みみろる', inputName: 'みみろる' },
      { id: '0428', name: 'みみろっぷ', inputName: 'みみろっふ゜' },
      { id: '0442', name: 'みかるげ', inputName: 'みかるけ゛' },
      { id: '0501', name: 'みじゅまる', inputName: 'みし゛ゅまる' },
      { id: '0504', name: 'みねずみ', inputName: 'みねす゛み' },
      { id: '0505', name: 'みるほっぐ', inputName: 'みるほっく゛' },
      { id: '0778', name: 'みみっきゅ', inputName: 'みみっきゅ' },
      { id: '0856', name: 'みぶりむ', inputName: 'みふ゛りむ' },
      { id: '0928', name: 'みにーぶ', inputName: 'みにーふ゛' },
      { id: '0968', name: 'みみずず', inputName: 'みみす゛す゛' },
      { id: '0976', name: 'みがるーさ', inputName: 'みか゛るーさ' },
      { id: '1008', name: 'みらいどん', inputName: 'みらいと゛ん' },
    ],
    [
      { id: '0200', name: 'むうま', inputName: 'むうま' },
      { id: '0238', name: 'むちゅーる', inputName: 'むちゅーる' },
      { id: '0396', name: 'むっくる', inputName: 'むっくる' },
      { id: '0397', name: 'むくばーど', inputName: 'むくは゛ーと゛' },
      { id: '0398', name: 'むくほーく', inputName: 'むくほーく' },
      { id: '0429', name: 'むうまーじ', inputName: 'むうまーし゛' },
      { id: '0508', name: 'むーらんど', inputName: 'むーらんと゛' },
      { id: '0517', name: 'むんな', inputName: 'むんな' },
      { id: '0518', name: 'むしゃーな', inputName: 'むしゃーな' },
      { id: '0890', name: 'むげんだいな', inputName: 'むけ゛んた゛いな' },
    ],
    [
      { id: '0072', name: 'めのくらげ', inputName: 'めのくらけ゛' },
      { id: '0132', name: 'めたもん', inputName: 'めたもん' },
      { id: '0154', name: 'めがにうむ', inputName: 'めか゛にうむ' },
      { id: '0179', name: 'めりーぷ', inputName: 'めりーふ゜' },
      { id: '0375', name: 'めたんぐ', inputName: 'めたんく゛' },
      { id: '0376', name: 'めたぐろす', inputName: 'めたく゛ろす' },
      { id: '0469', name: 'めがやんま', inputName: 'めか゛やんま' },
      { id: '0551', name: 'めぐろこ', inputName: 'めく゛ろこ' },
      { id: '0586', name: 'めぶきじか', inputName: 'めふ゛きし゛か' },
      { id: '0586-1', name: 'めぶきじか', inputName: 'めふ゛きし゛か' },
      { id: '0586-2', name: 'めぶきじか', inputName: 'めふ゛きし゛か' },
      { id: '0586-3', name: 'めぶきじか', inputName: 'めふ゛きし゛か' },
      { id: '0636', name: 'めらるば', inputName: 'めらるは゛' },
      { id: '0648', name: 'めろえった', inputName: 'めろえった' },
      { id: '0648-1', name: 'めろえった', inputName: 'めろえった' },
      { id: '0703', name: 'めれしー', inputName: 'めれしー' },
      { id: '0774', name: 'めての', inputName: 'めての' },
      { id: '0774-1', name: 'めての', inputName: 'めての' },
      { id: '0808', name: 'めるたん', inputName: 'めるたん' },
      { id: '0809', name: 'めるめたる', inputName: 'めるめたる' },
      { id: '0816', name: 'めっそん', inputName: 'めっそん' },
    ],
    [
      { id: '0114', name: 'もんじゃら', inputName: 'もんし゛ゃら' },
      { id: '0180', name: 'もここ', inputName: 'もここ' },
      { id: '0391', name: 'もうかざる', inputName: 'もうかさ゛る' },
      { id: '0465', name: 'もじゃんぼ', inputName: 'もし゛ゃんほ゛' },
      { id: '0529', name: 'もぐりゅー', inputName: 'もく゛りゅー' },
      { id: '0546', name: 'もんめん', inputName: 'もんめん' },
      { id: '0591', name: 'もろばれる', inputName: 'もろは゛れる' },
      { id: '0633', name: 'ものず', inputName: 'ものす゛' },
      { id: '0722', name: 'もくろー', inputName: 'もくろー' },
      { id: '0873', name: 'もすのう', inputName: 'もすのう' },
      { id: '0877', name: 'もるぺこ', inputName: 'もるへ゜こ' },
      { id: '0877-1', name: 'もるぺこ', inputName: 'もるへ゜こ' },
      { id: '0967', name: 'もととかげ', inputName: 'もととかけ゛' },
      { id: '1025', name: 'ももわろう', inputName: 'ももわろう' },
    ],
  ],
  '08': [
    [
      { id: '0079', name: 'やどん', inputName: 'やと゛ん' },
      { id: '0079-1', name: 'やどん', inputName: 'やと゛ん' },
      { id: '0080', name: 'やどらん', inputName: 'やと゛らん' },
      { id: '0080-1', name: 'やどらん', inputName: 'やと゛らん' },
      { id: '0193', name: 'やんやんま', inputName: 'やんやんま' },
      { id: '0198', name: 'やみからす', inputName: 'やみからす' },
      { id: '0199', name: 'やどきんぐ', inputName: 'やと゛きんく゛' },
      { id: '0199-1', name: 'やどきんぐ', inputName: 'やと゛きんく゛' },
      { id: '0288', name: 'やるきもの', inputName: 'やるきもの' },
      { id: '0302', name: 'やみらみ', inputName: 'やみらみ' },
      { id: '0343', name: 'やじろん', inputName: 'やし゛ろん' },
      { id: '0511', name: 'やなっぷ', inputName: 'やなっふ゜' },
      { id: '0512', name: 'やなっきー', inputName: 'やなっきー' },
      { id: '0568', name: 'やぶくろん', inputName: 'やふ゛くろん' },
      { id: '0661', name: 'ややこま', inputName: 'ややこま' },
      { id: '0674', name: 'やんちゃむ', inputName: 'やんちゃむ' },
      { id: '0734', name: 'やんぐーす', inputName: 'やんく゛ーす' },
      { id: '0757', name: 'やとうもり', inputName: 'やとうもり' },
      { id: '0765', name: 'やれゆーたん', inputName: 'やれゆーたん' },
      { id: '0850', name: 'やくで', inputName: 'やくて゛' },
      { id: '0854', name: 'やばちゃ', inputName: 'やは゛ちゃ' },
      { id: '1013', name: 'やばそちゃ', inputName: 'やは゛そちゃ' },
    ],
    [
      { id: '0064', name: 'ゆんげらー', inputName: 'ゆんけ゛らー' },
      { id: '0346', name: 'ゆれいどる', inputName: 'ゆれいと゛る' },
      { id: '0361', name: 'ゆきわらし', inputName: 'ゆきわらし' },
      { id: '0459', name: 'ゆきかぶり', inputName: 'ゆきかふ゛り' },
      { id: '0460', name: 'ゆきのおー', inputName: 'ゆきのおー' },
      { id: '0478', name: 'ゆきめのこ', inputName: 'ゆきめのこ' },
      { id: '0480', name: 'ゆくしー', inputName: 'ゆくしー' },
      { id: '0577', name: 'ゆにらん', inputName: 'ゆにらん' },
      { id: '0872', name: 'ゆきはみ', inputName: 'ゆきはみ' },
    ],
    [
      { id: '0164', name: 'よるのずく', inputName: 'よるのす゛く' },
      { id: '0246', name: 'よーぎらす', inputName: 'よーき゛らす' },
      { id: '0355', name: 'よまわる', inputName: 'よまわる' },
      { id: '0477', name: 'よのわーる', inputName: 'よのわーる' },
      { id: '0506', name: 'よーてりー', inputName: 'よーてりー' },
      { id: '0746', name: 'よわし', inputName: 'よわし' },
      { id: '0746-1', name: 'よわし', inputName: 'よわし' },
      { id: '0820', name: 'よくばりす', inputName: 'よくは゛りす' },
    ],
  ],
  '09': [
    [
      { id: '0020', name: 'らった', inputName: 'らった' },
      { id: '0020-1', name: 'らった', inputName: 'らった' },
      { id: '0026', name: 'らいちゅう', inputName: 'らいちゅう' },
      { id: '0026-1', name: 'らいちゅう', inputName: 'らいちゅう' },
      { id: '0045', name: 'らふれしあ', inputName: 'らふれしあ' },
      { id: '0113', name: 'らっきー', inputName: 'らっきー' },
      { id: '0131', name: 'らぷらす', inputName: 'らふ゜らす' },
      { id: '0171', name: 'らんたーん', inputName: 'らんたーん' },
      { id: '0243', name: 'らいこう', inputName: 'らいこう' },
      { id: '0260', name: 'らぐらーじ', inputName: 'らく゛らーし゛' },
      { id: '0280', name: 'らるとす', inputName: 'らるとす' },
      { id: '0309', name: 'らくらい', inputName: 'らくらい' },
      { id: '0310', name: 'らいぼると', inputName: 'らいほ゛ると' },
      { id: '0370', name: 'らぶかす', inputName: 'らふ゛かす' },
      { id: '0409', name: 'らむぱるど', inputName: 'らむは゜ると゛' },
      { id: '0579', name: 'らんくるす', inputName: 'らんくるす' },
      { id: '0608', name: 'らんぷらー', inputName: 'らんふ゜らー' },
      { id: '0645', name: 'らんどろす', inputName: 'らんと゛ろす' },
      { id: '0645-1', name: 'らんどろす', inputName: 'らんと゛ろす' },
      { id: '0754', name: 'ららんてす', inputName: 'ららんてす' },
      { id: '0814', name: 'らびふっと', inputName: 'らひ゛ふっと' },
      { id: '0905', name: 'らぶとろす', inputName: 'らふ゛とろす' },
      { id: '0905-1', name: 'らぶとろす', inputName: 'らふ゛とろす' },
      { id: '0911', name: 'らうどぼーん', inputName: 'らうと゛ほ゛ーん' },
    ],
    [
      { id: '0005', name: 'りざーど', inputName: 'りさ゛ーと゛' },
      { id: '0006', name: 'りざーどん', inputName: 'りさ゛ーと゛ん' },
      { id: '0217', name: 'りんぐま', inputName: 'りんく゛ま' },
      { id: '0345', name: 'りりーら', inputName: 'りりーら' },
      { id: '0433', name: 'りーしゃん', inputName: 'りーしゃん' },
      { id: '0447', name: 'りおる', inputName: 'りおる' },
      { id: '0605', name: 'りぐれー', inputName: 'りく゛れー' },
      { id: '0949', name: 'りくくらげ', inputName: 'りくくらけ゛' },
      { id: '0981', name: 'りききりん', inputName: 'りききりん' },
    ],
    [
      { id: '0124', name: 'るーじゅら', inputName: 'るーし゛ゅら' },
      { id: '0249', name: 'るぎあ', inputName: 'るき゛あ' },
      { id: '0272', name: 'るんぱっぱ', inputName: 'るんは゜っは゜' },
      { id: '0298', name: 'るりり', inputName: 'るりり' },
      { id: '0337', name: 'るなとーん', inputName: 'るなとーん' },
      { id: '0404', name: 'るくしお', inputName: 'るくしお' },
      { id: '0448', name: 'るかりお', inputName: 'るかりお' },
      { id: '0701', name: 'るちゃぶる', inputName: 'るちゃふ゛る' },
      { id: '0745', name: 'るがるがん', inputName: 'るか゛るか゛ん' },
      { id: '0745-1', name: 'るがるがん', inputName: 'るか゛るか゛ん' },
      { id: '0745-2', name: 'るがるがん', inputName: 'るか゛るか゛ん' },
      { id: '0792', name: 'るなあーら', inputName: 'るなあーら' },
    ],
    [
      { id: '0082', name: 'れあこいる', inputName: 'れあこいる' },
      { id: '0377', name: 'れじろっく', inputName: 'れし゛ろっく' },
      { id: '0378', name: 'れじあいす', inputName: 'れし゛あいす' },
      { id: '0379', name: 'れじすちる', inputName: 'れし゛すちる' },
      { id: '0384', name: 'れっくうざ', inputName: 'れっくうさ゛' },
      { id: '0405', name: 'れんとらー', inputName: 'れんとらー' },
      { id: '0486', name: 'れじぎがす', inputName: 'れし゛き゛か゛す' },
      { id: '0510', name: 'れぱるだす', inputName: 'れは゜るた゛す' },
      { id: '0643', name: 'れしらむ', inputName: 'れしらむ' },
      { id: '0825', name: 'れどーむし', inputName: 'れと゛ーむし' },
      { id: '0894', name: 'れじえれき', inputName: 'れし゛えれき' },
      { id: '0895', name: 'れじどらご', inputName: 'れし゛と゛らこ゛' },
      { id: '0897', name: 'れいすぽす', inputName: 'れいすほ゜す' },
    ],
    [
      { id: '0037', name: 'ろこん', inputName: 'ろこん' },
      { id: '0037-1', name: 'ろこん', inputName: 'ろこん' },
      { id: '0315', name: 'ろぜりあ', inputName: 'ろせ゛りあ' },
      { id: '0407', name: 'ろずれいど', inputName: 'ろす゛れいと゛' },
      { id: '0479-1', name: 'ろとむ', inputName: 'ろとむ' },
      { id: '0479-2', name: 'ろとむ', inputName: 'ろとむ' },
      { id: '0479-3', name: 'ろとむ', inputName: 'ろとむ' },
      { id: '0479-4', name: 'ろとむ', inputName: 'ろとむ' },
      { id: '0479-5', name: 'ろとむ', inputName: 'ろとむ' },
    ],
  ],
  '10': [
    [
      { id: '0066', name: 'わんりきー', inputName: 'わんりきー' },
      { id: '0158', name: 'わにのこ', inputName: 'わにのこ' },
      { id: '0189', name: 'わたっこ', inputName: 'わたっこ' },
      { id: '0256', name: 'わかしゃも', inputName: 'わかしゃも' },
      { id: '0552', name: 'わるびる', inputName: 'わるひ゛る' },
      { id: '0553', name: 'わるびある', inputName: 'わるひ゛ある' },
      { id: '0830', name: 'わたしらが', inputName: 'わたしらか゛' },
      { id: '0835', name: 'わんぱち', inputName: 'わんは゜ち' },
      { id: '0918', name: 'わないだー', inputName: 'わないた゛ー' },
      { id: '0924', name: 'わっかねずみ', inputName: 'わっかねす゛み' },
    ],
    [{ id: '0988', name: 'ちをはうはね', inputName: 'ちをはうはね' }],
    [
      { id: '0307', name: 'あさなん', inputName: 'あさなん' },
      { id: '0224', name: 'おくたん', inputName: 'おくたん' },
      { id: '0627', name: 'わしぼん', inputName: 'わしほ゛ん' },
      { id: '0534', name: 'ろーぶしん', inputName: 'ろーふ゛しん' },
    ],
  ],
  '11': [
    [
      { id: '0105', name: 'がらがら', inputName: 'か゛らか゛ら' },
      { id: '0115', name: 'がるーら', inputName: 'か゛るーら' },
      { id: '0414', name: 'がーめいる', inputName: 'か゛ーめいる' },
      { id: '0444', name: 'がばいと', inputName: 'か゛は゛いと' },
      { id: '0445', name: 'がぶりあす', inputName: 'か゛ふ゛りあす' },
      { id: '0525', name: 'がんとる', inputName: 'か゛んとる' },
      { id: '0536', name: 'がまがる', inputName: 'か゛まか゛る' },
      { id: '0537', name: 'がまげろげ', inputName: 'か゛まけ゛ろけ゛' },
      { id: '0689', name: 'がめのです', inputName: 'か゛めのて゛す' },
      { id: '0697', name: 'がちごらす', inputName: 'か゛ちこ゛らす' },
      { id: '0727', name: 'がおがえん', inputName: 'か゛おか゛えん' },
      { id: '0901', name: 'がちぐま', inputName: 'か゛ちく゛ま' },
      { id: '0901-1', name: 'がちぐま', inputName: 'か゛ちく゛ま' },
      { id: '0950', name: 'がけがに', inputName: 'か゛けか゛に' },
    ],
    [
      { id: '0078', name: 'ぎゃろっぷ', inputName: 'き゛ゃろっふ゜' },
      { id: '0130', name: 'ぎゃらどす', inputName: 'き゛ゃらと゛す' },
      { id: '0526', name: 'ぎがいあす', inputName: 'き゛か゛いあす' },
      { id: '0599', name: 'ぎある', inputName: 'き゛ある' },
      { id: '0600', name: 'ぎぎある', inputName: 'き゛き゛ある' },
      { id: '0601', name: 'ぎぎぎある', inputName: 'き゛き゛き゛ある' },
      { id: '0681', name: 'ぎるがるど', inputName: 'き゛るか゛ると゛' },
      { id: '0681-1', name: 'ぎるがるど', inputName: 'き゛るか゛ると゛' },
      { id: '0860', name: 'ぎもー', inputName: 'き゛もー' },
    ],
    [
      { id: '0207', name: 'ぐらいがー', inputName: 'く゛らいか゛ー' },
      { id: '0210', name: 'ぐらんぶる', inputName: 'く゛らんふ゛る' },
      { id: '0262', name: 'ぐらえな', inputName: 'く゛らえな' },
      { id: '0383', name: 'ぐらーどん', inputName: 'く゛らーと゛ん' },
      { id: '0453', name: 'ぐれっぐる', inputName: 'く゛れっく゛る' },
      { id: '0471', name: 'ぐれいしあ', inputName: 'く゛れいしあ' },
      { id: '0472', name: 'ぐらいおん', inputName: 'く゛らいおん' },
      { id: '0768', name: 'ぐそくむしゃ', inputName: 'く゛そくむしゃ' },
      { id: '0915', name: 'ぐるとん', inputName: 'く゛るとん' },
      { id: '0936', name: 'ぐれんあるま', inputName: 'く゛れんあるま' },
    ],
    [
      { id: '0094', name: 'げんがー', inputName: 'け゛んか゛ー' },
      {
        id: '0382-1',
        name: 'げんしかいおーが',
        inputName: 'け゛んしかいおーか゛',
      },
      {
        id: '0383-1',
        name: 'げんしぐらーどん',
        inputName: 'け゛んしく゛らーと゛ん',
      },
      { id: '0649', name: 'げのせくと', inputName: 'け゛のせくと' },
      { id: '0657', name: 'げこがしら', inputName: 'け゛こか゛しら' },
      { id: '0658', name: 'げっこうが', inputName: 'け゛っこうか゛' },
    ],
    [
      { id: '0042', name: 'ごるばっと', inputName: 'こ゛るは゛っと' },
      { id: '0055', name: 'ごるだっく', inputName: 'こ゛るた゛っく' },
      { id: '0067', name: 'ごーりきー', inputName: 'こ゛ーりきー' },
      { id: '0075', name: 'ごろーん', inputName: 'こ゛ろーん' },
      { id: '0076', name: 'ごろーにゃ', inputName: 'こ゛ろーにゃ' },
      { id: '0092', name: 'ごーす', inputName: 'こ゛ーす' },
      { id: '0093', name: 'ごーすと', inputName: 'こ゛ーすと' },
      { id: '0231', name: 'ごまぞう', inputName: 'こ゛まそ゛う' },
      { id: '0293', name: 'ごにょにょ', inputName: 'こ゛にょにょ' },
      { id: '0316', name: 'ごくりん', inputName: 'こ゛くりん' },
      { id: '0392', name: 'ごうかざる', inputName: 'こ゛うかさ゛る' },
      { id: '0446', name: 'ごんべ', inputName: 'こ゛んへ゛' },
      { id: '0574', name: 'ごちむ', inputName: 'こ゛ちむ' },
      { id: '0575', name: 'ごちみる', inputName: 'こ゛ちみる' },
      { id: '0576', name: 'ごちるぜる', inputName: 'こ゛ちるせ゛る' },
      { id: '0622', name: 'ごびっと', inputName: 'こ゛ひ゛っと' },
      { id: '0623', name: 'ごるーぐ', inputName: 'こ゛るーく゛' },
      { id: '0673', name: 'ごーごーと', inputName: 'こ゛ーこ゛ーと' },
      { id: '0675', name: 'ごろんだ', inputName: 'こ゛ろんた゛' },
      { id: '0812', name: 'ごりらんだー', inputName: 'こ゛りらんた゛ー' },
    ],
  ],
  '12': [
    [
      { id: '0335', name: 'ざんぐーす', inputName: 'さ゛んく゛ーす' },
      { id: '0893', name: 'ざるーど', inputName: 'さ゛るーと゛' },
    ],
    [
      { id: '0087', name: 'じゅごん', inputName: 'し゛ゅこ゛ん' },
      { id: '0253', name: 'じゅぷとる', inputName: 'し゛ゅふ゜とる' },
      { id: '0254', name: 'じゅかいん', inputName: 'し゛ゅかいん' },
      { id: '0263', name: 'じぐざぐま', inputName: 'し゛く゛さ゛く゛ま' },
      { id: '0354', name: 'じゅぺった', inputName: 'し゛ゅへ゜った' },
      { id: '0369', name: 'じーらんす', inputName: 'し゛ーらんす' },
      { id: '0385', name: 'じらーち', inputName: 'し゛らーち' },
      { id: '0462', name: 'じばこいる', inputName: 'し゛は゛こいる' },
      { id: '0496', name: 'じゃのびー', inputName: 'し゛ゃのひ゛ー' },
      { id: '0497', name: 'じゃろーだ', inputName: 'し゛ゃろーた゛' },
      { id: '0634', name: 'じへっど', inputName: 'し゛へっと゛' },
      { id: '0718', name: 'じがるで', inputName: 'し゛か゛るて゛' },
      { id: '0718-1', name: 'じがるで', inputName: 'し゛か゛るて゛' },
      { id: '0718-2', name: 'じがるで', inputName: 'し゛か゛るて゛' },
      { id: '0724', name: 'じゅないぱー', inputName: 'し゛ゅないは゜ー' },
      { id: '0780', name: 'じじーろん', inputName: 'し゛し゛ーろん' },
      { id: '0782', name: 'じゃらこ', inputName: 'し゛ゃらこ' },
      { id: '0783', name: 'じゃらんご', inputName: 'し゛ゃらんこ゛' },
      { id: '0784', name: 'じゃららんが', inputName: 'し゛ゃららんか゛' },
      { id: '0817', name: 'じめれおん', inputName: 'し゛めれおん' },
      { id: '0884', name: 'じゅらるどん', inputName: 'し゛ゅらると゛ん' },
    ],
    [
      { id: '0041', name: 'ずばっと', inputName: 'す゛は゛っと' },
      { id: '0408', name: 'ずがいどす', inputName: 'す゛か゛いと゛す' },
      { id: '0559', name: 'ずるっぐ', inputName: 'す゛るっく゛' },
      { id: '0560', name: 'ずるずきん', inputName: 'す゛るす゛きん' },
      { id: '0806', name: 'ずがどーん', inputName: 'す゛か゛と゛ーん' },
      { id: '0938', name: 'ずぴか', inputName: 'す゛ひ゜か' },
    ],
    [
      { id: '0007', name: 'ぜにがめ', inputName: 'せ゛にか゛め' },
      { id: '0523', name: 'ぜぶらいか', inputName: 'せ゛ふ゛らいか' },
      { id: '0644', name: 'ぜくろむ', inputName: 'せ゛くろむ' },
      { id: '0716', name: 'ぜるねあす', inputName: 'せ゛るねあす' },
      { id: '0807', name: 'ぜらおら', inputName: 'せ゛らおら' },
    ],
    [
      { id: '0570', name: 'ぞろあ', inputName: 'そ゛ろあ' },
      { id: '0571', name: 'ぞろあーく', inputName: 'そ゛ろあーく' },
      { id: '0878', name: 'ぞうどう', inputName: 'そ゛うと゛う' },
    ],
  ],
  '13': [
    [
      { id: '0051', name: 'だぐとりお', inputName: 'た゛く゛とりお' },
      { id: '0275', name: 'だーてんぐ', inputName: 'た゛ーてんく゛' },
      { id: '0374', name: 'だんばる', inputName: 'た゛んは゛る' },
      { id: '0476', name: 'だいのーず', inputName: 'た゛いのーす゛' },
      { id: '0491', name: 'だーくらい', inputName: 'た゛ーくらい' },
      { id: '0503', name: 'だいけんき', inputName: 'た゛いけんき' },
      { id: '0524', name: 'だんごろ', inputName: 'た゛んこ゛ろ' },
      { id: '0539', name: 'だげき', inputName: 'た゛け゛き' },
      { id: '0554', name: 'だるまっか', inputName: 'た゛るまっか' },
      { id: '0569', name: 'だすとだす', inputName: 'た゛すとた゛す' },
      { id: '0578', name: 'だぶらん', inputName: 'た゛ふ゛らん' },
      { id: '0781', name: 'だだりん', inputName: 'た゛た゛りん' },
      { id: '0879', name: 'だいおうどう', inputName: 'た゛いおうと゛う' },
      { id: '0891', name: 'だくま', inputName: 'た゛くま' },
    ],
    [{ id: '0737', name: 'でんぢむし', inputName: 'て゛んち゛むし' }],
    [{ id: '0933', name: 'じおづむ', inputName: 'し゛おつ゛む' }],
    [
      { id: '0181', name: 'でんりゅう', inputName: 'て゛んりゅう' },
      { id: '0225', name: 'でりばーど', inputName: 'て゛りは゛ーと゛' },
      { id: '0228', name: 'でるびる', inputName: 'て゛るひ゛る' },
      { id: '0386', name: 'でおきしす', inputName: 'て゛おきしす' },
      { id: '0386-1', name: 'でおきしす', inputName: 'て゛おきしす' },
      { id: '0386-2', name: 'でおきしす', inputName: 'て゛おきしす' },
      { id: '0386-3', name: 'でおきしす', inputName: 'て゛おきしす' },
      { id: '0562', name: 'ですます', inputName: 'て゛すます' },
      { id: '0563', name: 'ですかーん', inputName: 'て゛すかーん' },
      { id: '0596', name: 'でんちゅら', inputName: 'て゛んちゅら' },
      { id: '0702', name: 'ででんね', inputName: 'て゛て゛んね' },
      { id: '0735', name: 'でかぐーす', inputName: 'て゛かく゛ーす' },
      { id: '0796', name: 'でんじゅもく', inputName: 'て゛んし゛ゅもく' },
      { id: '0867', name: 'ですばーん', inputName: 'て゛すは゛ーん' },
      { id: '0959', name: 'でかぬちゃん', inputName: 'て゛かぬちゃん' },
    ],
    [
      { id: '0073', name: 'どくくらげ', inputName: 'と゛くくらけ゛' },
      { id: '0084', name: 'どーどー', inputName: 'と゛ーと゛ー' },
      { id: '0085', name: 'どーどりお', inputName: 'と゛ーと゛りお' },
      { id: '0109', name: 'どがーす', inputName: 'と゛か゛ーす' },
      { id: '0235', name: 'どーぶる', inputName: 'と゛ーふ゛る' },
      { id: '0269', name: 'どくけいる', inputName: 'と゛くけいる' },
      { id: '0294', name: 'どごーむ', inputName: 'と゛こ゛ーむ' },
      { id: '0322', name: 'どんめる', inputName: 'と゛んめる' },
      { id: '0339', name: 'どじょっち', inputName: 'と゛し゛ょっち' },
      { id: '0389', name: 'どだいとす', inputName: 'と゛た゛いとす' },
      { id: '0430', name: 'どんからす', inputName: 'と゛んからす' },
      { id: '0436', name: 'どーみらー', inputName: 'と゛ーみらー' },
      { id: '0437', name: 'どーたくん', inputName: 'と゛ーたくん' },
      { id: '0452', name: 'どらぴおん', inputName: 'と゛らひ゜おん' },
      { id: '0454', name: 'どくろっぐ', inputName: 'と゛くろっく゛' },
      { id: '0464', name: 'どさいどん', inputName: 'と゛さいと゛ん' },
      { id: '0530', name: 'どりゅうず', inputName: 'と゛りゅうす゛' },
      { id: '0532', name: 'どっこらー', inputName: 'と゛っこらー' },
      { id: '0533', name: 'どてっこつ', inputName: 'と゛てっこつ' },
      { id: '0691', name: 'どらみどろ', inputName: 'と゛らみと゛ろ' },
      { id: '0733', name: 'どでかばし', inputName: 'と゛て゛かは゛し' },
      { id: '0748', name: 'どひどいで', inputName: 'と゛ひと゛いて゛' },
      { id: '0749', name: 'どろばんこ', inputName: 'と゛ろは゛んこ' },
      { id: '0885', name: 'どらめしや', inputName: 'と゛らめしや' },
      { id: '0886', name: 'どろんち', inputName: 'と゛ろんち' },
      { id: '0887', name: 'どらぱると', inputName: 'と゛らは゜ると' },
      { id: '0980', name: 'どおー', inputName: 'と゛おー' },
      { id: '0983', name: 'どどげざん', inputName: 'と゛と゛け゛さ゛ん' },
    ],
  ],
  '14': [
    [
      { id: '0012', name: 'ばたふりー', inputName: 'は゛たふりー' },
      { id: '0122', name: 'ばりやーど', inputName: 'は゛りやーと゛' },
      { id: '0157', name: 'ばくふーん', inputName: 'は゛くふーん' },
      { id: '0236', name: 'ばるきー', inputName: 'は゛るきー' },
      { id: '0248', name: 'ばんぎらす', inputName: 'は゛んき゛らす' },
      { id: '0257', name: 'ばしゃーも', inputName: 'は゛しゃーも' },
      { id: '0295', name: 'ばくおんぐ', inputName: 'は゛くおんく゛' },
      { id: '0313', name: 'ばるびーと', inputName: 'は゛るひ゛ーと' },
      { id: '0323', name: 'ばくーだ', inputName: 'は゛くーた゛' },
      { id: '0325', name: 'ばねぶー', inputName: 'は゛ねふ゛ー' },
      { id: '0513', name: 'ばおっぷ', inputName: 'は゛おっふ゜' },
      { id: '0514', name: 'ばおっきー', inputName: 'は゛おっきー' },
      { id: '0582', name: 'ばにぷっち', inputName: 'は゛にふ゜っち' },
      { id: '0583', name: 'ばにりっち', inputName: 'は゛にりっち' },
      { id: '0584', name: 'ばいばにら', inputName: 'は゛いは゛にら' },
      { id: '0595', name: 'ばちゅる', inputName: 'は゛ちゅる' },
      { id: '0626', name: 'ばっふろん', inputName: 'は゛っふろん' },
      { id: '0629', name: 'ばるちゃい', inputName: 'は゛るちゃい' },
      { id: '0630', name: 'ばるじーな', inputName: 'は゛るし゛ーな' },
      { id: '0710', name: 'ばけっちゃ', inputName: 'は゛けっちゃ' },
      { id: '0750', name: 'ばんばどろ', inputName: 'は゛んは゛と゛ろ' },
      { id: '0776', name: 'ばくがめす', inputName: 'は゛くか゛めす' },
      { id: '0811', name: 'ばちんきー', inputName: 'は゛ちんきー' },
      { id: '0832', name: 'ばいうーるー', inputName: 'は゛いうーるー' },
      { id: '0866', name: 'ばりこおる', inputName: 'は゛りこおる' },
      { id: '0871', name: 'ばちんうに', inputName: 'は゛ちんうに' },
      { id: '0898', name: 'ばどれっくす', inputName: 'は゛と゛れっくす' },
      { id: '0900', name: 'ばさぎり', inputName: 'は゛さき゛り' },
    ],
    [
      { id: '0013', name: 'びーどる', inputName: 'ひ゛ーと゛る' },
      { id: '0100', name: 'びりりだま', inputName: 'ひ゛りりた゛ま' },
      { id: '0329', name: 'びぶらーば', inputName: 'ひ゛ふ゛らーは゛' },
      { id: '0399', name: 'びっぱ', inputName: 'ひ゛っは゜' },
      { id: '0400', name: 'びーだる', inputName: 'ひ゛ーた゛る' },
      { id: '0416', name: 'びーくいん', inputName: 'ひ゛ーくいん' },
      { id: '0640', name: 'びりじおん', inputName: 'ひ゛りし゛おん' },
      { id: '0666', name: 'びびよん', inputName: 'ひ゛ひ゛よん' },
    ],
    [
      { id: '0126', name: 'ぶーばー', inputName: 'ふ゛ーは゛ー' },
      { id: '0136', name: 'ぶーすたー', inputName: 'ふ゛ーすたー' },
      { id: '0197', name: 'ぶらっきー', inputName: 'ふ゛らっきー' },
      { id: '0209', name: 'ぶるー', inputName: 'ふ゛るー' },
      { id: '0326', name: 'ぶーぴっぐ', inputName: 'ふ゛ーひ゜っく゛' },
      { id: '0418', name: 'ぶいぜる', inputName: 'ふ゛いせ゛る' },
      { id: '0432', name: 'ぶにゃっと', inputName: 'ふ゛にゃっと' },
      { id: '0467', name: 'ぶーばーん', inputName: 'ふ゛ーは゛ーん' },
      { id: '0652', name: 'ぶりがろん', inputName: 'ふ゛りか゛ろん' },
      { id: '0693', name: 'ぶろすたー', inputName: 'ふ゛ろすたー' },
      { id: '0858', name: 'ぶりむおん', inputName: 'ふ゛りむおん' },
      { id: '0896', name: 'ぶりざぽす', inputName: 'ふ゛りさ゛ほ゜す' },
      { id: '0965', name: 'ぶろろん', inputName: 'ふ゛ろろん' },
      { id: '0966', name: 'ぶろろろーむ', inputName: 'ふ゛ろろろーむ' },
      { id: '1018', name: 'ぶりじゅらす', inputName: 'ふ゛りし゛ゅらす' },
    ],
    [
      { id: '0088', name: 'べとべたー', inputName: 'へ゛とへ゛たー' },
      { id: '0089', name: 'べとべとん', inputName: 'へ゛とへ゛とん' },
      { id: '0108', name: 'べろりんが', inputName: 'へ゛ろりんか゛' },
      { id: '0153', name: 'べいりーふ', inputName: 'へ゛いりーふ' },
      { id: '0463', name: 'べろべると', inputName: 'へ゛ろへ゛ると' },
      { id: '0803', name: 'べべのむ', inputName: 'へ゛へ゛のむ' },
      { id: '0859', name: 'べろばー', inputName: 'へ゛ろは゛ー' },
      { id: '0954', name: 'べらかす', inputName: 'へ゛らかす' },
    ],
    [
      { id: '0306', name: 'ぼすごどら', inputName: 'ほ゛すこ゛と゛ら' },
      { id: '0373', name: 'ぼーまんだ', inputName: 'ほ゛ーまんた゛' },
      { id: '0708', name: 'ぼくれー', inputName: 'ほ゛くれー' },
      { id: '0721', name: 'ぼるけにおん', inputName: 'ほ゛るけにおん' },
      { id: '0971', name: 'ぼち', inputName: 'ほ゛ち' },
    ],
  ],
  '15': [
    [
      { id: '0046', name: 'ぱらす', inputName: 'は゜らす' },
      { id: '0047', name: 'ぱらせくと', inputName: 'は゜らせくと' },
      { id: '0086', name: 'ぱうわう', inputName: 'は゜うわう' },
      { id: '0327', name: 'ぱっちーる', inputName: 'は゜っちーる' },
      { id: '0366', name: 'ぱーるる', inputName: 'は゜ーるる' },
      { id: '0417', name: 'ぱちりす', inputName: 'は゜ちりす' },
      { id: '0484', name: 'ぱるきあ', inputName: 'は゜るきあ' },
      { id: '0484-1', name: 'ぱるきあ', inputName: 'は゜るきあ' },
      { id: '0711', name: 'ぱんぷじん', inputName: 'は゜んふ゜し゛ん' },
      { id: '0836', name: 'ぱるすわん', inputName: 'は゜るすわん' },
      { id: '0880', name: 'ぱっちらごん', inputName: 'は゜っちらこ゛ん' },
      { id: '0881', name: 'ぱっちるどん', inputName: 'は゜っちると゛ん' },
      { id: '0921', name: 'ぱも', inputName: 'は゜も' },
      { id: '0922', name: 'ぱもっと', inputName: 'は゜もっと' },
      { id: '0923', name: 'ぱーもっと', inputName: 'は゜ーもっと' },
      { id: '0926', name: 'ぱぴもっち', inputName: 'は゜ひ゜もっち' },
      { id: '1002', name: 'ぱおじあん', inputName: 'は゜おし゛あん' },
    ],
    [
      { id: '0017', name: 'ぴじょん', inputName: 'ひ゜し゛ょん' },
      { id: '0018', name: 'ぴじょっと', inputName: 'ひ゜し゛ょっと' },
      { id: '0025', name: 'ぴかちゅう', inputName: 'ひ゜かちゅう' },
      { id: '0035', name: 'ぴっぴ', inputName: 'ひ゜っひ゜' },
      { id: '0036', name: 'ぴくしー', inputName: 'ひ゜くしー' },
      { id: '0172', name: 'ぴちゅー', inputName: 'ひ゜ちゅー' },
      { id: '0440', name: 'ぴんぷく', inputName: 'ひ゜んふ゜く' },
    ],
    [
      { id: '0039', name: 'ぷりん', inputName: 'ふ゜りん' },
      { id: '0040', name: 'ぷくりん', inputName: 'ふ゜くりん' },
      { id: '0142', name: 'ぷてら', inputName: 'ふ゜てら' },
      { id: '0174', name: 'ぷぷりん', inputName: 'ふ゜ふ゜りん' },
      { id: '0311', name: 'ぷらする', inputName: 'ふ゜らする' },
      { id: '0564', name: 'ぷろとーが', inputName: 'ふ゜ろとーか゛' },
    ],
    [
      { id: '0053', name: 'ぺるしあん', inputName: 'へ゜るしあん' },
      { id: '0279', name: 'ぺりっぱー', inputName: 'へ゜りっは゜ー' },
      { id: '0441', name: 'ぺらっぷ', inputName: 'へ゜らっふ゜' },
      { id: '0545', name: 'ぺんどらー', inputName: 'へ゜んと゛らー' },
      { id: '0684', name: 'ぺろっぱふ', inputName: 'へ゜ろっは゜ふ' },
      { id: '0685', name: 'ぺろりーむ', inputName: 'へ゜ろりーむ' },
    ],
    [
      { id: '0016', name: 'ぽっぽ', inputName: 'ほ゜っほ゜' },
      { id: '0077', name: 'ぽにーた', inputName: 'ほ゜にーた' },
      { id: '0137', name: 'ぽりごん', inputName: 'ほ゜りこ゛ん' },
      { id: '0188', name: 'ぽぽっこ', inputName: 'ほ゜ほ゜っこ' },
      { id: '0261', name: 'ぽちえな', inputName: 'ほ゜ちえな' },
      { id: '0351', name: 'ぽわるん', inputName: 'ほ゜わるん' },
      { id: '0393', name: 'ぽっちゃま', inputName: 'ほ゜っちゃま' },
      { id: '0394', name: 'ぽったいし', inputName: 'ほ゜ったいし' },
      { id: '0498', name: 'ぽかぶ', inputName: 'ほ゜かふ゛' },
    ],
  ],
};
